
--Select all data from Customers table
SELECT * FROM Customers;

--Select data from Customers table where customer_id = 3
SELECT * FROM Customers WHERE customer_id = 11;

--Select data from Products table where price is greater than 5
SELECT * FROM Products WHERE price > 5;

--Select data from Products table where category_id is either 1 or 2
SELECT * FROM Products WHERE category_id IN (1, 2);

--Select data from Products table ordered by price in descending order
SELECT * FROM Products ORDER BY price DESC;

--Select the total number of products in each category
SELECT Category.name, COUNT(Products.product_id) AS total_products
FROM Products
INNER JOIN Category ON Products.category_id = Category.category_id
GROUP BY Category.name;

--Select the total inventory value for each supplier
SELECT Suppliers.name, SUM(Products.inventory_level * Products.price) AS inventory_value
FROM Products
INNER JOIN Suppliers ON Products.supplier_id = Suppliers.supplier_id
GROUP BY Suppliers.name;


--Retrieve all products with a weight greater than 10 lbs:
SELECT * FROM Products WHERE weight > 10;

--Retrieve the total revenue generated by a specific product:
SELECT SUM(total_amount) AS revenue
FROM Orders 
WHERE product_id = '4';

--Retrieve the top 5 best-selling products:
SELECT Products.name, SUM(Orders.quantity) AS total_quantity 
FROM Products 
JOIN Orders ON Products.product_id = Orders.product_id 
GROUP BY Products.name 
ORDER BY total_quantity DESC 
LIMIT 5;

--Retrieve all invoices for a specific customer:
SELECT Invoices.invoice_id, Invoices.invoice_date, Invoices.total_amount , Customers.name AS customer_name
FROM Invoices 
JOIN Orders ON Invoices.order_id = Orders.order_id 
JOIN Customers ON Orders.customer_id = Customers.customer_id 
WHERE Customers.customer_id = 1;




--Retrieve the total revenue generated by all sales in a given time period:
SELECT SUM(total_amount) AS revenue 
FROM Invoices
WHERE invoice_date BETWEEN '2022-01-02' AND '2022-01-04';

--Retrieve the name and contact information of all suppliers who provide products in a specific category:
SELECT DISTINCT Suppliers.name, Suppliers.contact_info 
FROM Suppliers 
JOIN Products ON Products.supplier_id = Suppliers.supplier_id 
WHERE Products.category_id = '3';


--Retrieve the name and address of all customers who have placed an order in a specific time period:
SELECT DISTINCT Customers.name, Customers.address 
FROM Customers 
JOIN Orders ON Orders.customer_id = Customers.customer_id 
WHERE Orders.order_date BETWEEN '2022-01-01' AND '2022-01-04';





SELECT * FROM Customers;